## Floor and Ceilings

In [36]:
import numpy

numpy.set_printoptions(sign=' ')
arreglo = numpy.array(list(map(float,input().split())))

print(numpy.floor(arreglo))
print(numpy.ceil(arreglo))
print(numpy.rint(arreglo))


 1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9


[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [34]:
import numpy

numpy.set_printoptions(sign=' ')

a = numpy.array(input().split(),float)

print(numpy.floor(a))
print(numpy.ceil(a))
print(numpy.rint(a))

 1.2 3.1 125


[   1.    3.  125.]
[   2.    4.  125.]
[   1.    3.  125.]
