## Numpy Zeros

In [10]:
import numpy

entrada = list(map(int,input().split(' ')))

print(numpy.zeros(entrada, dtype = numpy.int))
print(numpy.ones(entrada, dtype = numpy.int))

 3 3 3


[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
