Universidad Galileo

Ciencia de Datos en Python

PAPD - Sección V

Sergio José Barrios Martínez

Carnet No. 19012765

# Ejercicios Matrices




In [1]:
import numpy as np
import matplotlib.pyplot as plt

### Constructores de matrices

NumPy provee diversas funciones para crear matrices , algunas de las cuales ya vimos cuando estudiamos vectores , la diferencia consiste en que ahora ya no usamos un número para indicar el tamaño de un vector, si no una **tupla** de 2 elementos: (m,n) . Algunas de las funciones  que aplican tanto a vectores como a matrices son:

* np.array: crear una matriz a partir de una lista de listas: cada fila es una sublista
* np.zeros: crear una matriz de ceros
* np.ones: crear una matriz de unos
* np.empty: crear una matriz sin importarnos sus valores
* np.full: crear una matriz  con cierto valor
* np.copy: crea un clon o copia de cierta matriz

Algunas funciones específicas de matrices son:

* np.matrix: resultado casi identico a la función mas general np.array ,pero posee algunas propiedades adicionales específicas de listas, por ejemplo notación sencilla para inversas de matrices.
* np.eye: crear una matriz con 1s en su diagonal principal y ceros en el resto
* np.identity : crear una matriz identidad

Algunas funciones que solo aplican a vectores y no a matrices son:

* np.arange
* np.linspace

Existen otras pero estas son posiblemente las mas comunes. Puedes consultar las otras disponibles en: https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html


## Ejercicio No. 1

**Ejercicio**: Investigar y ejemplificar diferencias entre np.array y np.matrix

Como se mencionó anteriormente, **numpy.matrix** tiene propiedades específicas para listas, enfocadas para el uso de matrices, es decir, se limita a arreglos bi-dimensionales. **numpy.array** es más general, pudiéndose extender a arreglos multidimensionales. Desde este punto de vista, *numpy.matrix* es un caso específico de *numpy.array*, (de hecho *numpy.matrix* es una sub-clase de **ndarrays** y tiene los mismos métodos y características de esta clase).


Sin embargo, internamente, sí se hace una distinción de qué tipo de arreglo son. Por ejemplo:

In [2]:
a = np.array([[1,2,3]]) # Para formar una matriz, se especifica una lista de listas
print(a,type(a),np.ndim(a))
b = np.matrix([1,2,3]) # Para formar una matrix, únicamente se especifican las listas
print(b,type(b),np.ndim(b))

[[1 2 3]] <class 'numpy.ndarray'> 2
[[1 2 3]] <class 'numpy.matrix'> 2


Tanto los *nd.arrays* como las *np.matrix* comparten algunas operaciones aritméticas, e incluso matriciales, por ejemplo:
* Operador +,-,T,I

In [3]:
transpuesta_a = a.T
transpuesta_b = b.T
print (transpuesta_a)
print (transpuesta_b)

[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


Sin embargo, hay propiedades que solamente se encuentran en el objeto tipo *matrix*, por ejemplo, la propiedad **"I"** para retornar la matriz inversa y la propiedad **"H"** para retornar la inversa conjugada, algo que no tienen los np.arrays:

In [4]:
print (b.I)
print (b.H)

[[0.07142857]
 [0.14285714]
 [0.21428571]]
[[1]
 [2]
 [3]]


El operador de potenciación ****** también se comporta diferente. En el caso de los np.arrays, aplicar el operador $**$2 devuelve cada elemento elevado al cuadrado, mientras que en matrices, devuelve la matrix multiplicada por ella misma. Por ejemplo:

In [5]:
c_array = np.array([[1,2],[3,4]])
print(c_array**2) # Potenciación 2 elemento a elemento
c_matriz = np.matrix([[1,2],[3,4]]) # Multiplicación Matricial c * c
print(c_matriz**2)

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


## Multiplicación Matricial

**Ejemplo en DS** : en inteligencia artificial y ML en la sub-rama "reinforcement learning" la "ecuacion de bellman" puede aplicarse de manera vectorizada a traves del operar vectores, matrices y escalares en una sola expresion.

<img src="https://rebornhugo.github.io/assets/images/post_images/%E5%BC%BA%E5%8C%96%E5%AD%A6%E4%B9%A02/bellman%20equation2.PNG">

* n = numero de estados del sistema.
* V(s) = vector que representa el valor esperado para cierto estado
* R = recompensa inmediata percibida por el agente al salir de cierto estado.(vector)
* P = matriz de transicion de la cadena de Markov sub-yacente.(matriz)
* γ = factor de descuento de recompensas futuras(escalar)


## Ejercicio No. 2
Calcular V(s) para el siguiente sistema aplicando la ecuación de bellman de manera vectorizada.

In [6]:
V = np.array([0,0,0]) # valor inicial de V(s)
R = np.array([10,2,5]) # vector de recompensas
P = np.array([[0.5,0.25,0.25],
              [0.2,0.40,0.40],
              [0.80,0.10,0.10]])  # matriz de transición
gamma = 0.99

In [7]:
# Cálculo de V(s) de manera vectorizada
V = R + np.matmul(gamma*P,V) # Función "matmul" para general la multiplicación matricial
print(V)

[10.  2.  5.]


## Ejercicio No. 2 

Implementar en una funcion neural_network(X) la red neuronal definida por la siguiente arquitectura:

<img src="http://i.imgur.com/UNlffE1.png">

Podemos validar si fue correctamente implementada si usamos como entrada el vector x=[1,1] . Debemos obtener el resultado mostrado en la imagen.

In [8]:
# Se definirán dos funciones, una para aceptar un vector "X" de 2x1 (neural_network_v),
# y otra para aceptar un vector "X" de 1x2 (neutral_network_h) para verificar cómo
# cambia la operatoria. Para implementación real, únicamente necesitaríamos una de las
# dos, y valiéndonos de la función SHAPE adecuar (por medio de TRANSPOSE) la forma de
# la entrada "X". Para este ejercicio se implementan ambas funciones para ser más explícitos 
# en la operatoria que se requeriría en cada caso.

# Función para la Red Neuronal, con X una capa de entrada de (2x1)
def neural_network_v(X):
    
    # Matriz de Pesos para la Capa de Entrada "X" (3x2)
    H1_W = np.array([[0.712,0.112],
                     [0.355,0.855],
                     [0.268,0.468]])

    # Bias sobre la capa oculta (deducida de la información) (3x1)
    BIAS_H1 = np.array([[-0.13],
                        [-0.44],
                        [-0.06]])
    
    # Matriz de Pesos para la Capa de Salida "OL"
    OL_W = np.array([[0.116,0.329,0.708]])
    
    # Bias sobre la capa de salida (deducida de la información) (1x1)
    BIAS_OL = np.array([-0.12]),

    H1 = np.matmul(H1_W,X)
    print("Capa Oculta Sin Bias:")
    print(H1)
    H1+=BIAS_H1
    print("Capa Oculta Con Bias:")
    print(H1)
    OL = np.matmul(OL_W,H1)
    print("Capa Salida Sin Bias:")
    print(OL)
    OL+=BIAS_OL
    print("Capa Salida Con Bias:")
    print(OL)
    
    return


# Función para la Red Neuronal, con X una capa de entrada de (1x2)
def neural_network_h(X):
    
    # Matriz de Pesos para la Capa de Entrada "X" (3x2)
    H1_W = np.array([[0.712,0.355,0.268],
                     [0.112,0.855,0.468]])

    # Bias sobre la capa oculta (deducida de la información) (3x1)
    BIAS_H1 = np.array([-0.13,-0.44,-0.06])
    
    # Matriz de Pesos para la Capa de Salida "OL"
    OL_W = np.array([[0.116],[0.329],[0.708]])
    
    # Bias sobre la capa de salida (deducida de la información) (1x1)
    BIAS_OL = np.array(-0.12),

    H1 = np.matmul(X,H1_W)
    print("Capa Oculta Sin Bias:")
    print(H1)
    H1+=BIAS_H1
    print("Capa Oculta Con Bias:")
    print(H1)
    OL = np.matmul(H1,OL_W)
    print("Capa Salida Sin Bias:")
    print(OL)
    OL+=BIAS_OL
    print("Capa Salida Con Bias:")
    print(OL)
    
    return

In [9]:
#Prueba para vector "X" de 2x1
X =  np.array([[1],[1]])
neural_network_v(X)

Capa Oculta Sin Bias:
[[0.824]
 [1.21 ]
 [0.736]]
Capa Oculta Con Bias:
[[0.694]
 [0.77 ]
 [0.676]]
Capa Salida Sin Bias:
[[0.812442]]
Capa Salida Con Bias:
[[0.692442]]


In [10]:
#Prueba para vector "X" de 1x2
X =  np.array([1,1])
neural_network_h(X)

Capa Oculta Sin Bias:
[0.824 1.21  0.736]
Capa Oculta Con Bias:
[0.694 0.77  0.676]
Capa Salida Sin Bias:
[0.812442]
Capa Salida Con Bias:
[0.692442]


Una vez tenemos la implementacion correcta, cambiar la funcion de activacion de la capa de salida por la funcion de activacion ReLu(https://en.wikipedia.org/wiki/Rectifier_(neural_networks)):

<img src="https://cdn-images-1.medium.com/max/1600/1*DfMRHwxY1gyyDmrIAd-gjQ.png">

Luego evaluar la red neuronal sobre la matriz de datos X(de manera vectorizada):

In [11]:
# Función de Activación ReLu
# Se utiliza piecewise para definirla
def ReLu(x):
    k=np.piecewise(x,[x<0,x>=0],[lambda x: 0,lambda x: x])
    return(k)

In [12]:
# Función para la Red Neuronal, con X una capa de entrada de (1x2)
def neural_network(X):
    
    # Matriz de Pesos para la Capa de Entrada "X" (3x2)
    H1_W = np.array([[0.712,0.355,0.268],
                     [0.112,0.855,0.468]])

    # Bias sobre la capa oculta (deducida de la información) (3x1)
    BIAS_H1 = np.array([-0.13,-0.44,-0.06])
    
    # Matriz de Pesos para la Capa de Salida "OL"
    OL_W = np.array([[0.116],[0.329],[0.708]])
    
    # Bias sobre la capa de salida (deducida de la información) (1x1)
    BIAS_OL = np.array(-0.12),

    H1 = np.matmul(X,H1_W)
    print("Capa Oculta Sin Bias:")
    print(H1)
    H1+=BIAS_H1
    print("Capa Oculta Con Bias:")
    print(H1)
    H1 = ReLu(H1)
    print("Capa Oculta Con Bias y ReLu:")
    print(H1)   
    OL = np.matmul(H1,OL_W)
    print("Capa Salida Sin Bias:")
    print(OL)
    OL+=BIAS_OL
    print("Capa Salida Con Bias:")
    print(OL)
    OL = ReLu(OL)
    print("Capa Salida Con Bias y ReLu:")
    print(OL)   
    
    return

In [13]:
#Prueba para vector "X" de 1x2
X =  np.array([1,1])
neural_network(X)

Capa Oculta Sin Bias:
[0.824 1.21  0.736]
Capa Oculta Con Bias:
[0.694 0.77  0.676]
Capa Oculta Con Bias y ReLu:
[0.694 0.77  0.676]
Capa Salida Sin Bias:
[0.812442]
Capa Salida Con Bias:
[0.692442]
Capa Salida Con Bias y ReLu:
[0.692442]


Como se puede observar, en este caso específico con X=[1,1] los resultados no cambian, ya que cada salida (en la capa oculta y la capa de salida propiamente) es mayor que cero para esta X, y la función de activación ReLu la deja "pasar" sin cambios.